apiVersion: v1
kind: Service
metadata:
  name: auth
  {{- with .Values.auth.service.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
  selector:
    app: auth
