apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"  # Lower weight means it runs first
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation