apiVersion: v1
kind: Service
metadata:
  name: api
  {{- with .Values.api.service.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  selector:
    app: api