apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-vectordb-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    # "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-vectordb-migration
    spec:
      restartPolicy: Never
      containers:
        - name: vectordb-migration
          image: "{{ .Values.global.ecr.registry }}/{{ .Values.vectordb.migration.image.repository }}:{{ .Values.vectordb.migration.image.tag }}"
          imagePullPolicy: {{ .Values.vectordb.migration.image.pullPolicy }}
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /app/packages/vector
              echo "Starting migration..."
              export DATABASE_URL=$BASE_DB_URL
              export DIRECT_URL=$BASE_DB_URL
              echo "$DATABASE_URL" | (head -c 10 && echo "..." && echo "$DATABASE_URL" | tail -c 10)
              pnpm prisma db execute --file ./scripts/create.sql
              export DATABASE_URL=$VECTOR_DB_URL
              export DIRECT_URL=$VECTOR_DB_URL
              echo "$DATABASE_URL" | (head -c 10 && echo "..." && echo "$DATABASE_URL" | tail -c 10)
              pnpm prisma db execute --file ./scripts/pgvector.sql
              if pnpm prisma migrate deploy; then
                echo "Migration completed successfully"
                exit 0
              else
                echo "Migration failed"
                exit 1
              fi
          envFrom:
            - configMapRef:
                name: vectordb-config
          env:
            - name: BASE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
            - name: VECTOR_DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: vectorDbUrl
