apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greptile.fullname" . }}-env
  labels:
    {{- include "greptile.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env.shared }}
  {{ $k }}: {{ tpl ($v | toString) $ | quote }}
  {{- end }}
