{{- range $name, $component := .Values.components }}
{{- $isJackson := eq $name "jackson" }}
{{- $isAuth := eq $name "auth" }}
{{- $isAuthV2 := eq $name "auth-v2" }}
{{- if and $component.enabled (or (not $isJackson) $.Values.saml.enabled) (or (not $isAuth) (not $.Values.authV2.enabled)) (or (not $isAuthV2) $.Values.authV2.enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greptile.componentName" (dict "root" $ "name" $name) }}-env
  labels:
    {{- include "greptile.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
data:
  SERVICE_NAME: {{ $name | quote }}
  {{- range $k, $v := $component.componentEnv }}
  {{ $k }}: {{ tpl ($v | toString) $ | quote }}
  {{- end }}
{{- end }}
{{- end }}
