{{- range $name, $component := .Values.components }}
{{- if and $component.enabled $component.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greptile.componentName" (dict "root" $ "name" $name) }}-secrets
  labels:
    {{- include "greptile.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := $component.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
