{{- range $name, $component := .Values.components }}
{{- $isJackson := eq $name "jackson" }}
{{- $isAuth := eq $name "auth" }}
{{- $isAuthV2 := eq $name "auth-v2" }}
{{- if and $component.enabled $component.service.enabled (or (not $isJackson) $.Values.saml.enabled) (or (not $isAuth) (not $.Values.authV2.enabled)) (or (not $isAuthV2) $.Values.authV2.enabled) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greptile.componentName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "greptile.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $component.service.type }}
  ports:
    - name: http
      port: {{ $component.service.port }}
      targetPort: {{ $component.containerPort }}
      protocol: TCP
      {{- if and (eq $component.service.type "NodePort") $component.service.nodePort }}
      nodePort: {{ $component.service.nodePort }}
      {{- end }}
  selector:
    {{- include "greptile.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
