apiVersion: v1
kind: Service
metadata:
  name: jackson
  {{- with .Values.jackson.service.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  type: {{ .Values.jackson.service.type }}
  ports:
    - port: {{ .Values.jackson.service.port }}
      targetPort: {{ .Values.jackson.service.port }}
  selector:
    app: jackson
