apiVersion: v2
name: greptile
description: A Helm chart for Greptile
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://greptile.com
maintainers:
  - name: Greptile
    email: support@greptile.com

dependencies:
  - name: postgresql
    version: "16.7.14"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "21.2.6"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 
