services:
  greptile_web_service:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/web:dev-build
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - APP_URL=${APP_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GREPTILE_AUTH_SERVER=${GREPTILE_AUTH_SERVER}
      - GREPTILE_API_URL=${GREPTILE_API_URL}
      - AUTH_SECRET=${JWT_SECRET}
      - GITHUB_ENABLED=${GITHUB_ENABLED}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER}
      - AUTH_EMAIL_FROM=${AUTH_EMAIL_FROM}
    ports:
      - "3000:3000"

  greptile_auth_service:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/auth:dev-build
    platform: linux/amd64
    environment:
      - LOG_FORMAT=json
      - APP_URL=${APP_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_FROM=${AUTH_EMAIL_FROM}
    ports:
      - "3001:3001"

  greptile_api_service:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/api:dev-build
    platform: linux/amd64
    restart: on-failure
    environment:
      - LOG_FORMAT=json
      - URL=${API_URL}
      - APP_URL=${APP_URL}
      - QUERY_URL=${QUERY_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      # - DATABASE_USERNAME=${DB_USER}
      # - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - EMBEDDINGS_MODEL_PROVIDER=${EMBEDDINGS_MODEL_PROVIDER}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER}
      - VECTOR_DB_NAME=${VECTOR_DB_NAME}
      - VECTOR_DB_HOST=${VECTOR_DB_HOST}
      - VECTOR_DB_PORT=${VECTOR_DB_PORT}
      - VECTOR_DB_USER=${VECTOR_DB_USER}
      - VECTOR_DB_PASSWORD=${VECTOR_DB_PASSWORD}
      - BILLING=false
      - ANALYTICS=false
      - NOTIFICATIONS=false
      - NODE_ENV=production
      - X_AWS_REGION=${AWS_REGION}
      - PORT=3002
    ports:
      - "3002:3002"

  greptile_indexer_chunker:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/chunker:dev-build
    platform: linux/amd64
    restart: on-failure
    environment:
      - LOG_FORMAT=json
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - VECTOR_DB_USER=${DB_USER}
      - VECTOR_DB_PASSWORD=${DB_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER}
      - VECTOR_EMBEDDINGS_TABLE_NAME=${VECTOR_EMBEDDINGS_TABLE_NAME}
      - VECTOR_DB_NAME=${VECTOR_DB_NAME}
      - VECTOR_DB_HOST=${DB_HOST}
      - VECTOR_DB_PORT=${DB_PORT}
      - BATCH_SIZE=${BATCH_SIZE}
      - PORT=3003

  greptile_indexer_summarizer:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/summarizer:dev-build
    platform: linux/amd64
    restart: on-failure
    environment:
      - LOG_FORMAT=json
      - BATCH_SIZE=${BATCH_SIZE}
      - PARENT_DIR=/mnt/data/
      - DATABASE_URL=${DATABASE_URL}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - VECTOR_DB_USER=${DB_USER}
      - VECTOR_DB_PASSWORD=${DB_PASSWORD}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER}
      - VECTOR_EMBEDDINGS_TABLE_NAME=${VECTOR_EMBEDDINGS_TABLE_NAME}
      - VECTOR_DB_NAME=${VECTOR_DB_NAME}
      - VECTOR_DB_HOST=${DB_HOST}
      - VECTOR_DB_PORT=${DB_PORT}
      - PORT=3004
      - SUMMARIZER_MODEL_PROVIDER=${SUMMARIZER_MODEL_PROVIDER}
      - SUMMARIZER_MODEL=${SUMMARIZER_MODEL}
      - EMBEDDINGS_MODEL_PROVIDER=${EMBEDDINGS_MODEL_PROVIDER}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - AWS_REGION=${AWS_REGION}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_URL=${AZURE_OPENAI_URL}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME}
      - AZURE_OPENAI_EMBEDDINGS_API_VERSION=${AZURE_OPENAI_EMBEDDINGS_API_VERSION}

  greptile_webhook_service:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/webhook:dev-build
    platform: linux/amd64
    restart: on-failure
    environment:
      - PORT=3007
      - LOG_FORMAT=json
      - ANALYTICS=false
      # Dummy value for POSTHOG_KEY until bug fixed
      - POSTHOG_KEY=dummy_value
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_BOT_USERNAME=${GITHUB_BOT_USERNAME}
      - GITHUB_BOT_LOGIN=${GITHUB_BOT_LOGIN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - GREPTILE_API_URL=${API_URL}
      - WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - WORKER_HASH=${WORKER_HASH}
      - BATCH_SIZE=${BATCH_SIZE}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - GITHUB_VARS=""
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}
      - ANTHROPIC_KEY=${ANTHROPIC_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      # Any helicone openai token if necessary
    ports:
      - "3007:3007"
  
  greptile_reviews_service:
    image: 669869549360.dkr.ecr.us-east-1.amazonaws.com/greptile/reviews:dev-build
    platform: linux/amd64
    restart: on-failure
    environment:
      - GREPTILE_API_URL=${API_URL}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - ANALYTICS=false
      - BILLING=false
      - HATCHET_REVIEWER_SLOTS=2
      - HATCHET_REVIEWER_DURABLE_SLOTS=1000
      - ANTHROPIC_KEY=${ANTHROPIC_KEY}
      - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - EMBEDDINGS_MODEL_PROVIDER=${EMBEDDINGS_MODEL_PROVIDER}
      - REFINER_MODEL_PROVIDER=${REFINER_MODEL_PROVIDER}
      - SUMMARIZER_MODEL_PROVIDER=${SUMMARIZER_MODEL_PROVIDER}
      - AGENT_MODEL_PROVIDER=${AGENT_MODEL_PROVIDER}
      - CHAT_MODEL_PROVIDER=${CHAT_MODEL_PROVIDER}
      - MEMORY_CHAT_MODEL_PROVIDER=${MEMORY_CHAT_MODEL_PROVIDER}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_BOT_USERNAME=${GITHUB_BOT_USERNAME}
      - GITHUB_BOT_LOGIN=${GITHUB_BOT_LOGIN}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_URL=${AZURE_OPENAI_URL}
      - AZURE_OPENAI_EMBEDDINGS_API_VERSION=${AZURE_OPENAI_EMBEDDINGS_API_VERSION}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    ports:
      - "3005:3005"
