#!/bin/bash

# Check if .env file exists
if [ ! -f .env ]; then
    echo "Error: .env file not found in docker directory. Please create one from .env.example"
    exit 1
fi

# Function to generate random 32-character string
generate_random_string() {
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
}

# Populate JWT_SECRET if not already set or empty
if ! grep -q "^JWT_SECRET=.\+" .env; then
    echo "Generating JWT_SECRET..."
    random_string=$(generate_random_string)
    if grep -q "^JWT_SECRET=" .env; then
        # Update existing empty JWT_SECRET
        sed -i.bak "s/^JWT_SECRET=.*/JWT_SECRET=$random_string # Auto-generated by Greptile/" .env
    else
        # Add JWT_SECRET if it doesn't exist
        echo "JWT_SECRET=$random_string # Auto-generated by Greptile" >> .env
    fi
fi

# Populate TOKEN_ENCRYPTION_KEY if not already set or empty
if ! grep -q "^TOKEN_ENCRYPTION_KEY=.\+" .env; then
    echo "Generating TOKEN_ENCRYPTION_KEY..."
    random_string=$(generate_random_string)
    if grep -q "^TOKEN_ENCRYPTION_KEY=" .env; then
        # Update existing empty TOKEN_ENCRYPTION_KEY
        sed -i.bak "s/^TOKEN_ENCRYPTION_KEY=.*/TOKEN_ENCRYPTION_KEY=$random_string # Auto-generated by Greptile/" .env
    else
        # Add TOKEN_ENCRYPTION_KEY if it doesn't exist
        echo "TOKEN_ENCRYPTION_KEY=$random_string # Auto-generated by Greptile" >> .env
    fi
fi

# Define the list of services (kept for explicit starts, default to profile)
GREPTILE_SERVICES=(
    greptile_api_service
    greptile_auth_service
    greptile_indexer_chunker
    greptile_indexer_summarizer
    greptile_web_service
    greptile_webhook_service
    greptile_reviews_service
    greptile_jobs_service
)

# Check if Docker is accessible
if ! docker info > /dev/null 2>&1; then
    echo "Error: Cannot access Docker. Please check that:"
    echo "1. Docker is installed and running"
    echo "2. Your user has permission to access Docker (try running 'docker ps')"
    echo "3. You are a member of the 'docker' group (you can add yourself with 'sudo usermod -aG docker $USER')"
    exit 1
fi

echo "Starting Greptile services..."

# Start database migrations first
echo "Running database migrations..."
docker compose up -d greptile_postgres

# Check if migrations were successful
docker compose up greptile_db_migration_job --wait || { echo "DB migration failed"; exit 1; }

echo "Database migrations completed successfully."

# Start the core services
echo "Starting core services..."

# Check if SAML authentication should be enabled
COMPOSE_PROFILES=""
if [ "${AUTH_SAML_ONLY:-false}" = "true" ]; then
    echo "SAML authentication enabled - starting Jackson service..."
    COMPOSE_PROFILES="--profile saml"
fi

# Prefer using the greptile profile to start all app services together
docker compose up -d --force-recreate $COMPOSE_PROFILES --profile greptile 

# Copy SSL certificates to all services if CUSTOM_FILE_PATH is set
if [ -n "$CUSTOM_FILE_PATH" ]; then
    echo "Copying SSL certificates to services..."
    for service in "${GREPTILE_SERVICES[@]}"
    do
        # Get the container ID for the service
        container_id=$(docker compose ps -q $service 2>/dev/null)
        if [ -n "$container_id" ]; then
            echo "Copying to $service (container: $container_id)..."
            docker exec $container_id mkdir -p /app/custom_data
            docker cp $CUSTOM_FILE_PATH $container_id:/app/custom_data/
        else
            echo "Warning: Could not find container for service $service"
        fi
    done
fi

echo "All Greptile services have been started."
echo "You can check service status with: docker compose ps"
