#!/bin/bash

# Function to generate random 32-character string
generate_random_string() {
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
}

# Check if Docker is accessible
if ! docker info > /dev/null 2>&1; then
    echo "Error: Cannot access Docker. Please check that:"
    echo "1. Docker is installed and running"
    echo "2. Your user has permission to access Docker (try running 'docker ps')"
    echo "3. You are a member of the 'docker' group (you can add yourself with 'sudo usermod -aG docker $USER')"
    exit 1
fi

# Check if .env file exists
if [ ! -f .env ]; then
    echo "Error: .env file not found in docker directory. Please create one from .env.example"
    exit 1
fi

# Populate JWT_SECRET if not already set or empty
if ! grep -q "^JWT_SECRET=.\+" .env; then
    echo "Generating JWT_SECRET..."
    random_string=$(generate_random_string)
    if grep -q "^JWT_SECRET=" .env; then
        # Update existing empty JWT_SECRET
        sed -i.bak "s/^JWT_SECRET=.*/JWT_SECRET=$random_string # Auto-generated by Greptile/" .env
    else
        # Add JWT_SECRET if it doesn't exist
        echo "JWT_SECRET=$random_string # Auto-generated by Greptile" >> .env
    fi
fi

# Populate TOKEN_ENCRYPTION_KEY if not already set or empty
if ! grep -q "^TOKEN_ENCRYPTION_KEY=.\+" .env; then
    echo "Generating TOKEN_ENCRYPTION_KEY..."
    random_string=$(generate_random_string)
    if grep -q "^TOKEN_ENCRYPTION_KEY=" .env; then
        # Update existing empty TOKEN_ENCRYPTION_KEY
        sed -i.bak "s/^TOKEN_ENCRYPTION_KEY=.*/TOKEN_ENCRYPTION_KEY=$random_string # Auto-generated by Greptile/" .env
    else
        # Add TOKEN_ENCRYPTION_KEY if it doesn't exist
        echo "TOKEN_ENCRYPTION_KEY=$random_string # Auto-generated by Greptile" >> .env
    fi
fi

# Populate LLM_PROXY_KEY if not already set or empty
if ! grep -q "^LLM_PROXY_KEY=.\+" .env; then
    echo "Generating LLM_PROXY_KEY..."
    random_string=$(generate_random_string)
    if grep -q "^LLM_PROXY_KEY=" .env; then
        # Update existing empty LLM_PROXY_KEY
        sed -i.bak "s/^LLM_PROXY_KEY=.*/LLM_PROXY_KEY=$random_string # Auto-generated by Greptile/" .env
    else
        # Add LLM_PROXY_KEY if it doesn't exist
        echo "LLM_PROXY_KEY=$random_string # Auto-generated by Greptile" >> .env
    fi
fi

COMPOSE_PROFILES="--profile greptile"

echo "Starting Database..."
docker compose $COMPOSE_PROFILES up -d greptile_postgres

echo "Running database migrations..."
docker compose $COMPOSE_PROFILES up greptile_db_migration_job --wait || { echo "DB migration failed"; exit 1; }
echo "Database migrations completed successfully."

echo "Starting Greptile services..."

# Check if SAML authentication should be enabled
if [ "${AUTH_SAML_ONLY:-false}" = "true" ]; then
    echo "SAML authentication enabled - starting Jackson service..."
    COMPOSE_PROFILES="$COMPOSE_PROFILES --profile saml"
fi

# Only add --profile  with-db if the env var DB_HOST equals greptile-postgres
if [ "${DB_HOST:-greptile-postgres}" = "greptile-postgres" ]; then
    COMPOSE_PROFILES="$COMPOSE_PROFILES --profile with-db"
fi

# Prefer using the greptile profile to start all app services together
docker compose $COMPOSE_PROFILES up -d --force-recreate

echo "All Greptile services have been started."
echo "You can check service status with: docker compose ps"
