apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    # "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.global.ecr.registry }}/{{ .Values.database.migration.image.repository }}:{{ .Values.database.migration.image.tag }}"
          imagePullPolicy: {{ .Values.database.migration.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /app/packages/db
              echo "Starting migration..."
              pnpm prisma db execute --file ./scripts/create.sql
              pnpm prisma db execute --file ./scripts/hatchet.sql
              if pnpm prisma migrate deploy; then
                echo "Migration completed successfully"
                API_KEY=$(openssl rand -base64 32)
                sed "s|\$ORG_NAME|$ORG_NAME|g; s|\$TENANT_ID|$TENANT_ID|g; s|\$API_KEY|$API_KEY|g" ./scripts/root_org.sql > /tmp/processed.sql
                cat /tmp/processed.sql | pnpm prisma db execute --stdin || {
                  echo "Failed to execute root_org.sql"
                  cat /tmp/processed.sql
                  exit 1
                }
                exit 0
              else
                echo "Migration failed"
                exit 1
              fi
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: ORG_NAME
              value: {{ .Values.global.org.name }}
            - name: TENANT_ID
              value: {{ .Values.global.org.tenant }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url