
apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-11"
    {{- if .Values.aws.irsa.query }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsa.query.role }}
    {{- end }}
