{{- if .Values.github.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github
  annotations:
    "helm.sh/hook-weight": "0"
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.github.replicaCount }}
  selector:
    matchLabels:
      app: github
  template:
    metadata:
      labels:
        app: github
    spec:
      containers:
        - name: github
          image: "{{ .Values.global.ecr.registry }}/{{ .Values.github.image.repository }}:{{ .Values.github.image.tag }}"
          imagePullPolicy: {{ .Values.github.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.github.service.port }}
          envFrom:
            - configMapRef:
                name: github-config
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: clientId
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: clientSecret
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: webhookSecret
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: privateKey
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
          resources:
            {{- toYaml .Values.github.resources | nindent 12 }}
{{- end }}
