apiVersion: v1
kind: Service
metadata:
  name: web
  {{- with .Values.web.service.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
  selector:
    app: web

