apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackson
  annotations:
    "helm.sh/hook-weight": "0"
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.jackson.replicaCount }}
  selector:
    matchLabels:
      app: jackson
  template:
    metadata:
      labels:
        app: jackson
    spec:
      containers:
        - name: jackson
          image: "{{ .Values.jackson.image.repository }}:{{ .Values.jackson.image.tag }}"
          imagePullPolicy: {{ .Values.jackson.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.jackson.service.port }}
          envFrom:
            - configMapRef:
                name: jackson-config
          env: 
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
            - name: NEXTAUTH_ADMIN_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jacksonAdminCredentials
            - name: JACKSON_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: boxyhqApiKey
            - name: CLIENT_SECRET_VERIFIER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jacksonClientSecretVerifier
            - name: DB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jacksonDbEncryptionKey
            - name: HOST_URL 
              value: {{ .Values.jackson.config.url | replace "https://" "" | replace "http://" "" | default (printf "jackson.%s.svc.cluster.local:%v" .Release.Namespace .Values.jackson.service.port) }}
            - name: EXTERNAL_URL
              value: {{ .Values.jackson.config.url | default (printf "jackson.%s.svc.cluster.local:%v" .Release.Namespace .Values.jackson.service.port) }}
            - name: SAML_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: boxyhqSamlId
            - name: NEXTAUTH_URL
              value: {{ .Values.jackson.config.url | default (printf "jackson.%s.svc.cluster.local:%v" .Release.Namespace .Values.jackson.service.port) }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwtSecret
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jacksonPrivateKey
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jacksonPublicKey
          resources:
            {{- toYaml .Values.jackson.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.jackson.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.jackson.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30