apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  type: {{ .Values.indexer.service.type }}
  ports:
    - name: chunker
      port: {{ .Values.indexer.service.chunker.port }}
      targetPort: {{ .Values.indexer.service.chunker.port }}
    - name: summarizer
      port: {{ .Values.indexer.service.summarizer.port }}
      targetPort: {{ .Values.indexer.service.summarizer.port }}
  selector:
    app: indexer