apiVersion: v1
kind: Service
metadata:
  name: query
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - port: {{ .Values.query.service.port }}
      targetPort: {{ .Values.query.service.port }}
  selector:
    app: query