apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greptile.fullname" . }}-common-env
  labels:
    {{- include "greptile.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  # Container selection
  TAG: {{ .Values.global.imageTag | default "latest" }}
  ECR_REGISTRY: {{ .Values.global.ecr.registry }}
  
  # Database Configuration
  DB_HOST: {{ if .Values.postgresql.enabled }}{{ printf "%s-postgresql" (include "greptile.fullname" .) }}{{ else }}{{ .Values.database.host }}{{ end }}
  DB_PORT: "{{ if .Values.postgresql.enabled }}{{ .Values.postgresql.primary.service.port }}{{ else }}{{ .Values.database.port }}{{ end }}"
  DB_USER: {{ if .Values.postgresql.enabled }}postgres{{ else }}{{ .Values.database.user }}{{ end }}
  DB_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.postgresPassword }}{{ else }}{{ .Values.database.password }}{{ end }}
  
  # Vector Database Configuration
  VECTOR_DB_HOST: {{ if .Values.postgresql.enabled }}{{ printf "%s-postgresql" (include "greptile.fullname" .) }}{{ else }}{{ .Values.vectordb.host | default .Values.database.host }}{{ end }}
  VECTOR_DB_NAME: vector
  VECTOR_DB_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.postgresPassword }}{{ else }}{{ .Values.vectordb.password | default .Values.database.password }}{{ end }}
  VECTOR_DB_PORT: "{{ if .Values.postgresql.enabled }}{{ .Values.postgresql.primary.service.port }}{{ else }}{{ .Values.vectordb.port | default .Values.database.port }}{{ end }}"
  VECTOR_DB_PROVIDER: pgvector
  VECTOR_DB_USER: {{ if .Values.postgresql.enabled }}postgres{{ else }}{{ .Values.vectordb.user | default .Values.database.user }}{{ end }}
  VECTOR_EMBEDDINGS_TABLE_NAME: embeddings
  
  # Redis Configuration
  REDIS_PORT: "{{ if .Values.redis.enabled }}{{ .Values.redis.master.service.port }}{{ else }}{{ .Values.redis.port }}{{ end }}"
  REDIS_HOST: "{{ if .Values.redis.enabled }}{{ printf "%s-redis-master" (include "greptile.fullname" .) }}{{ else }}{{ .Values.redis.host }}{{ end }}"
  REDIS_USE_TLS: {{ .Values.redis.useTls | default false | quote }}

  # Service URLs
  GREPTILE_AUTH_SERVER: http://{{ include "greptile.fullname" . }}-auth:{{ .Values.auth.service.port | toString }}
  GREPTILE_API_URL: http://{{ include "greptile.fullname" . }}-api:{{ .Values.api.service.port | toString }}/v2
  GREPTILE_WEBHOOK_URL: http://{{ include "greptile.fullname" . }}-webhook:{{ .Values.webhook.service.port | toString }}/webhook
  API_URL: http://{{ include "greptile.fullname" . }}-api:{{ .Values.api.service.port | toString }}
  GITHUB_WEBHOOK_URL: http://{{ include "greptile.fullname" . }}-webhook:{{ .Values.webhook.service.port | toString }}/webhook
  GITLAB_WEBHOOK_URL: http://{{ include "greptile.fullname" . }}-webhook:{{ .Values.webhook.service.port | toString }}/webhook
  # TODO Remove QUERY_URL once query service is deprecated
  QUERY_URL: http://{{ include "greptile.fullname" . }}-query:8080/query
  
  # Authentication Configuration
  AUTH_BOXYHQ_SAML_ID: {{ .Values.jackson.config.samlId | default "dummy" | quote }}
  AUTH_BOXYHQ_SAML_SECRET: {{ .Values.jackson.config.samlSecret | default "dummy" | quote }}
  AUTH_BOXYHQ_SAML_ISSUER: {{ .Values.jackson.config.externalUrl | default (printf "http://localhost:%s" (.Values.jackson.service.port | toString)) | quote }}
  AUTH_BOXYHQ_URL: {{ .Values.jackson.config.externalUrl | default (printf "http://localhost:%s" (.Values.jackson.service.port | toString)) | quote }}
  
  # GitHub Configuration - Leave dummy values if unused
  GITHUB_ENABLED: "false"
  GITHUB_ENTERPRISE_ENABLED: "true"
  GITHUB_APP_ID: "1"
  GITHUB_APP_URL: "https://github.com/github-apps/dummy-app"
  GITHUB_CLIENT_ID: "Iv1.dummyb1c6c38481c"
  GITHUB_CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GITHUB_BOT_USERNAME: "greptile-bot-username"
  GITHUB_BOT_LOGIN: "greptile-apps-login"
  
  # GitHub Enterprise Configuration - Leave dummy values if unused
  GITHUB_ENTERPRISE_APP_URL: "https://github.your_org.com/github-apps/your_app"
  GITHUB_ENTERPRISE_APP_ID: "30"
  GITHUB_ENTERPRISE_API_URL: "https://github.your_org.com/api/v3/"
  GITHUB_ENTERPRISE_URL: "https://github.your_org.com"
  GITHUB_ENTERPRISE_CLIENT_ID: {{ .Values.global.authGithubId | default "Iv1.dummy" }}
  GITHUB_ENTERPRISE_CLIENT_SECRET: {{ .Values.global.authGithubSecret | default "client_Secret" }}
  AUTH_GITHUB_ID: {{ .Values.global.authGithubId | quote }}
  AUTH_GITHUB_SECRET: {{ .Values.global.authGithubSecret | quote }}
  
  # GitLab Configuration
  GITLAB_ENABLED: "true"
  
  # Email Configuration
  EMAIL_PROVIDER: {{ .Values.global.greptile.email.provider | quote }}
  
  # SMTP Configuration (used when EMAIL_PROVIDER is "SMTP")
  {{- if eq .Values.global.greptile.email.provider "SMTP" }}
  SMTP_HOST: {{ .Values.global.greptile.email.smtp.host | quote }}
  SMTP_PORT: {{ .Values.global.greptile.email.smtp.port | quote }}
  SMTP_USER: {{ .Values.global.greptile.email.smtp.user | quote }}
  SMTP_PASSWORD: {{ .Values.global.greptile.email.smtp.password | quote }}
  SMTP_SECURE: {{ .Values.global.greptile.email.smtp.secure | quote }}
  SMTP_TLS: {{ .Values.global.greptile.email.smtp.tls | quote }}
  SMTP_REJECT_UNAUTHORIZED: {{ .Values.global.greptile.email.smtp.rejectUnauthorized | quote }}
  {{- end }}
  
  # AWS SES Configuration (used when EMAIL_PROVIDER is "SES")
  {{- if eq .Values.global.greptile.email.provider "SES" }}
  {{- if .Values.global.greptile.email.ses.accessKeyId }}
  X_AWS_ACCESS_KEY_ID: {{ .Values.global.greptile.email.ses.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.global.greptile.email.ses.secretAccessKey }}
  X_AWS_SECRET_ACCESS_KEY: {{ .Values.global.greptile.email.ses.secretAccessKey | quote }}
  {{- end }}
  {{- end }}
  
  # LLM Configuration
  ANTHROPIC_BASE_URL: {{ .Values.global.ai.anthropic.baseUrl | quote }}
  REFINER_MODEL_PROVIDER: {{ .Values.global.ai.refiner.modelProvider | quote }}
  REFINER_MODEL: {{ .Values.global.ai.refiner.model | quote }}
  DISABLE_LLM_LOGGING: {{ .Values.global.ai.disableLlmLogging | quote }}
  CHAT_MODEL_PROVIDER: {{ .Values.global.ai.chat.modelProvider | quote }}
  MEMORY_CHAT_MODEL_PROVIDER: {{ .Values.global.ai.memory.chatModelProvider | quote }}
  MEMORY_CHAT_MODEL: {{ .Values.global.ai.memory.chatModel | quote }}
  SUMMARIZER_MODEL_PROVIDER: {{ .Values.global.ai.summarizer.modelProvider | quote }}
  SUMMARIZER_MODEL: {{ .Values.global.ai.summarizer.model | quote }}
  EMBEDDINGS_MODEL: {{ .Values.global.ai.embeddings.model | quote }}
  EMBEDDINGS_MODEL_PROVIDER: {{ .Values.global.ai.embeddings.modelProvider | quote }}
  OPENAI_API_BASE_URL: {{ .Values.global.ai.openai.apiBaseUrl | quote }}
  AZURE_OPENAI_URL: {{ .Values.global.ai.azure.openaiUrl | quote }}
  AZURE_OPENAI_SUMMARIZER_DEPLOYMENT_NAME: {{ .Values.global.ai.azure.openaiSummarizerDeploymentName | quote }}
  AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME: {{ .Values.global.ai.azure.openaiEmbeddingsDeploymentName | quote }}
  AZURE_OPENAI_SUMMARIZER_API_VERSION: {{ .Values.global.ai.azure.openaiSummarizerApiVersion | quote }}
  AZURE_OPENAI_EMBEDDINGS_API_VERSION: {{ .Values.global.ai.azure.openaiEmbeddingsApiVersion | quote }}
  AGENT_MODEL_PROVIDER: {{ .Values.global.ai.agent.modelProvider | quote }}
  AGENT_MODEL: {{ .Values.global.ai.agent.model | quote }}
  CHAT_MODEL: {{ .Values.global.ai.chat.model | quote }}
  DEFAULT_CHAT_MODEL: {{ .Values.global.ai.chat.model | quote }}
  
  # OAuth Gateway Configuration (optional)
  {{- if .Values.global.ai.oauthGateway.endpoint }}
  LLM_OAUTH_ENDPOINT: {{ .Values.global.ai.oauthGateway.endpoint | quote }}
  {{- end }}
  {{- if .Values.global.ai.oauthGateway.scope }}
  LLM_OAUTH_SCOPES: {{ .Values.global.ai.oauthGateway.scope | quote }}
  {{- end }}
  {{- if .Values.global.ai.oauthGateway.clientId }}
  LLM_GATEWAY_CLIENT_ID: {{ .Values.global.ai.oauthGateway.clientId | quote }}
  {{- end }}
  
  # Application Configuration
  BATCH_SIZE: {{ .Values.indexer.chunker.config.batchSize | default "99" | quote }}
  WORKER_HASH: "onprem"
  HATCHET_REVIEWER_SLOTS: {{ .Values.reviews.config.hatchetReviewerSlots | default "2" | quote }}
  HATCHET_REVIEWER_DURABLE_SLOTS: {{ .Values.reviews.config.hatchetReviewerDurableSlots | default "2" | quote }}
  LEARN_PROCEDURAL_MEMORY: {{ .Values.global.greptile.learnProceduralMemory | default "true" | quote }}
  USE_PROCEDURAL_MEMORY: {{ .Values.global.greptile.useProceduralMemory | default "true" | quote }}
  {{- if .Values.global.defaultTriggerOnUpdates }}
  DEFAULT_TRIGGER_ON_UPDATES: {{ .Values.global.defaultTriggerOnUpdates | quote }}
  {{- end }}
  
  # Memory Configuration (using cloud defaults)
  MEMORY_EVIDENCE_THRESHOLD: {{ .Values.global.greptile.memoryEvidenceThreshold | default "1" | quote }}
  MEMORY_LEARNING_CONFIDENCE_THRESHOLD: {{ .Values.global.greptile.memoryLearningConfidenceThreshold | default "0.15" | quote }}
  
  # LLM Behavior Controls (configurable via values.yaml if needed)
  {{- if .Values.global.ai.toolCallLimit }}
  TOOL_CALL_LIMIT: {{ .Values.global.ai.toolCallLimit | quote }}
  {{- end }}
  {{- if .Values.reviews.config.suggestionConfidenceThreshold }}
  SUGGESTION_CONFIDENCE_THRESHOLD: {{ .Values.reviews.config.suggestionConfidenceThreshold | quote }}
  {{- end }}
  
  # Review Configuration
  UPDATE_EXISTING_SUMMARY_COMMENT: {{ .Values.reviews.config.updateExistingSummaryComment | default "false" | quote }}
  
  # Integrations
  SLACK_WEBHOOK_URL: "test"
  SLACK_ENABLED: "false"
  
  # Perforce / Swarm (non-sensitive)
  P4USER: {{ .Values.global.perforce.p4user | default "" | quote }}
  P4PORT: {{ .Values.global.perforce.p4port | default "" | quote }}
  P4CLIENT: {{ .Values.global.perforce.p4client | default "" | quote }}
  P4_CHILD_PATHS: {{ .Values.global.perforce.p4childPaths | default "" | quote }}
  SWARM_URL: {{ .Values.global.perforce.swarmUrl | default "" | quote }}
  
  # Misc Configuration (hardcoded for on-prem)
  LOG_FORMAT: "json"
  ANALYTICS: "false"
  POSTHOG_KEY: "dummykey" # Leave dummy values for on-prem
  POSTHOG_HOST: "dummyhost" # Leave dummy values for on-prem
  BILLING: "false"
  BILLING_ENABLED: "false"
  NOTIFICATIONS: "false"
  HELICONE_KEY: ""
  HIDE_SOCIALS: "true"
  NODE_ENV: {{ .Values.global.environment | default "development" | quote }}
  LINEAR_ENABLED: "false"
  BENCHMARK: "false"
  AWS_REGION: "us-east-1"

  # Application URLs
  NEXTAUTH_URL: {{ .Values.global.externalUrl | default (printf "http://%s-web:%s" (include "greptile.fullname" .) (.Values.web.service.port | toString)) | quote }}
  
  # Email Configuration
  AUTH_EMAIL_FROM: {{ .Values.global.greptile.email.from | quote }}
  EMAIL_FROM: {{ .Values.global.greptile.email.from | quote }}

  # Additional LLM Configuration
  ANTHROPIC_KEY: {{ .Values.secrets.anthropicKey | quote }}
  OPENAI_KEY: {{ .Values.secrets.openaiKey | quote }}
  AZURE_OPENAI_KEY: {{ .Values.secrets.azureOpenaiKey | quote }}
  
  # Hatchet Configuration
  HATCHET_CLIENT_TOKEN: {{ .Values.secrets.hatchetClientToken | quote }}
  HATCHET_CLIENT_TLS_STRATEGY: "none"
  
  # GitHub Private Key
  GITHUB_PRIVATE_KEY: {{ .Values.secrets.githubPrivateKey | quote }}
  
  # Reviews Configuration
  INCLUDE_SUMMARY: {{ .Values.reviews.config.includeSummary | default "true" | quote }}
  SUMMARY_COLLAPSIBLE: {{ .Values.reviews.config.summaryCollapsible | default "true" | quote }}
  SUMMARY_DEFAULT_OPEN: {{ .Values.reviews.config.summaryDefaultOpen | default "true" | quote }}
  INCLUDE_ISSUES_TABLE: {{ .Values.reviews.config.includeIssuesTable | default "true" | quote }}
  ISSUES_TABLE_COLLAPSIBLE: {{ .Values.reviews.config.issuesTableCollapsible | default "true" | quote }}
  ISSUES_TABLE_DEFAULT_OPEN: {{ .Values.reviews.config.issuesTableDefaultOpen | default "true" | quote }}
  INCLUDE_CONFIDENCE_SCORE: {{ .Values.reviews.config.includeConfidenceScore | default "true" | quote }}
  CONFIDENCE_SCORE_COLLAPSIBLE: {{ .Values.reviews.config.confidenceScoreCollapsible | default "true" | quote }}
  CONFIDENCE_SCORE_DEFAULT_OPEN: {{ .Values.reviews.config.confidenceScoreDefaultOpen | default "true" | quote }}
  INCLUDE_SEQUENCE_DIAGRAM: {{ .Values.reviews.config.includeSequenceDiagram | default "true" | quote }}
  SEQUENCE_DIAGRAM_COLLAPSIBLE: {{ .Values.reviews.config.sequenceDiagramCollapsible | default "true" | quote }}
  SEQUENCE_DIAGRAM_DEFAULT_OPEN: {{ .Values.reviews.config.sequenceDiagramDefaultOpen | default "true" | quote }}
  PROMPT_TO_FIX_WITH_AI: {{ .Values.global.greptile.promptToFixWithAi | default "true" | quote }}
  
  # Additional Configuration
  GITHUB_ENTERPRISE_APP_PRIVATE_KEY: {{ .Values.secrets.githubPrivateKey | quote }} 
