apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greptile.fullname" . }}-secrets
  labels:
    {{- include "greptile.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
type: Opaque
data:
  # Authentication secrets
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  AUTH_SECRET: {{ .Values.secrets.authSecret | b64enc }}
  TOKEN_ENCRYPTION_KEY: {{ .Values.secrets.tokenEncryptionKey | b64enc }}
  
  # Webhook secrets
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | b64enc }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | b64enc }}
  
  # Hatchet configuration
  HATCHET_CLIENT_TOKEN: {{ .Values.secrets.hatchetClientToken | b64enc }}
  
  # LLM API keys
  ANTHROPIC_KEY: {{ .Values.secrets.anthropicKey | b64enc }}
  OPENAI_KEY: {{ .Values.secrets.openaiKey | b64enc }}
  AZURE_OPENAI_KEY: {{ .Values.secrets.azureOpenaiKey | b64enc }}
  
  # GitHub configuration
  GITHUB_PRIVATE_KEY: {{ .Values.secrets.githubPrivateKey | b64enc }}
  
  # GitLab configuration
  GLOBAL_GITLAB_TOKEN: {{ .Values.secrets.globalGitlabToken | b64enc }}
  
  # Database configuration
  DATABASE_URL: {{ include "greptile.databaseUrl" . | b64enc }}
  VECTOR_DB_URL: {{ include "greptile.vectorDatabaseUrl" . | b64enc }}
  DIRECT_URL: {{ include "greptile.databaseUrl" . | b64enc }}
  
  # Redis configuration
  REDIS_HOST: {{ include "greptile.redisUrl" . | b64enc }}