apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greptile.fullname" . }}-web-config
  labels:
    {{- include "greptile.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.web.service.port }}"
  NEXTAUTH_URL: {{ .Values.web.config.externalUrl | default (printf "http://%s-web:%s" (include "greptile.fullname" .) (.Values.web.service.port | toString)) | quote }}
  APP_URL: {{ .Values.web.config.externalUrl | default (printf "http://%s-web:%s" (include "greptile.fullname" .) (.Values.web.service.port | toString)) | quote }}
  AUTH_SAML_ONLY: {{ .Values.web.config.authSamlOnly | quote }}
  AUTH_TENANT: {{ .Values.web.config.authTenant | quote }}
  GLOBAL_GITLAB_BASE_URL: {{ .Values.web.config.globalGitlabBaseUrl | quote }}
  SKIP_COMPANY_ONBOARDING: {{ .Values.web.config.skipCompanyOnboarding | quote }}
  DEFAULT_CODE_PROVIDER: {{ .Values.web.config.defaultCodeProvider | quote }}
