#!/usr/bin/env bash
set -euo pipefail

log() {
  echo "[hatchet-token] $1"
}

PROJECT_DIR="/opt/greptile"
ENV_FILE="${PROJECT_DIR}/.env"
SENTINEL_FILE="${PROJECT_DIR}/.hatchet-token-ready"
TOKEN_FILE="${PROJECT_DIR}/.hatchet-token"
TENANT_ID_DEFAULT="707d0855-80ab-4e1f-a156-f1c4546cbf52"
TOKEN_NAME="auto-generated-by-greptile"
TOKEN_TTL="876000h"

[[ -f "$ENV_FILE" ]] || { log "Missing $ENV_FILE"; exit 1; }

# Extract tenant id from env file if present
get_env_value() {
  local key="$1"
  local value
  value=$(awk -F'=' -v k="$key" '
    $1==k {
      $1=""; sub(/^=/, ""); print $0
    }
  ' "$ENV_FILE" | head -n1)
  value="${value%%$'\r'}"
  value="${value%%\"}"
  value="${value##\"}"
  value="${value%%\'}"
  value="${value##\'}"
  echo "$value"
}

current_token() {
  get_env_value "HATCHET_CLIENT_TOKEN"
}

tenant_id=$(get_env_value "HATCHET_TENANT_ID")
if [[ -z "$tenant_id" ]]; then
  tenant_id="$TENANT_ID_DEFAULT"
fi

if [[ -s "$SENTINEL_FILE" && -n "$(current_token)" ]]; then
  log "Hatchet token already generated; skipping"
  exit 0
fi

wait_for_service() {
  local service="$1"
  local attempts=0
  local container_id=""
  while true; do
    container_id=$(docker compose --project-directory "$PROJECT_DIR" ps -q "$service" 2>/dev/null | head -n1 || true)
    if [[ -n "$container_id" ]]; then
      local status
      local health
      status=$(docker inspect -f '{{.State.Status}}' "$container_id" 2>/dev/null || true)
      health=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{end}}' "$container_id" 2>/dev/null || true)
      if [[ "$status" == "running" && ( -z "$health" || "$health" == "healthy" ) ]]; then
        return 0
      fi
      if [[ "$status" == "exited" || "$status" == "dead" ]]; then
        log "$service container exited unexpectedly"
        return 1
      fi
    fi
    (( attempts++ ))
    if (( attempts > 60 )); then
      log "Timed out waiting for $service to become healthy"
      return 1
    fi
    log "Waiting for $service..."
    sleep 5
  done
}

log "Ensuring hatchet services are healthy before generating token"
wait_for_service "rabbitmq"
wait_for_service "hatchet-api"
wait_for_service "hatchet-engine"

log "Generating Hatchet token for tenant $tenant_id"
set +o pipefail
new_token=$(docker compose --profile hatchet --project-directory "$PROJECT_DIR" run --rm --no-deps setup-config \
  /hatchet/hatchet-admin token create \
  --config /hatchet/config \
  --tenant-id "$tenant_id" \
  --name "$TOKEN_NAME" \
  --expiresIn "$TOKEN_TTL" | tr -d '\r')
status=$?
set -o pipefail

if [[ $status -ne 0 || -z "$new_token" ]]; then
  log "Failed to generate Hatchet token"
  exit 1
fi

log "Updating $ENV_FILE with new Hatchet token"
tmp_file=$(mktemp)
 awk -v token="$new_token" '
  BEGIN { inserted = 0 }
  /^# This token was automatically generated by Greptile$/ { next }
  /^HATCHET_CLIENT_TOKEN=/ { next }
  {
    print $0
    if ($0 ~ /^HATCHET_CLIENT_TLS_STRATEGY/) {
      print "# This token was automatically generated by Greptile"
      print "HATCHET_CLIENT_TOKEN=" token
      inserted = 1
    }
  }
  END {
    if (inserted == 0) {
      print ""
      print "# This token was automatically generated by Greptile"
      print "HATCHET_CLIENT_TOKEN=" token
    }
  }
 ' "$ENV_FILE" > "$tmp_file" && mv "$tmp_file" "$ENV_FILE"

# Persist token separately for debugging/condition checks
printf '%s' "$new_token" > "$TOKEN_FILE"
chmod 640 "$TOKEN_FILE"
chown root:docker "$TOKEN_FILE"
touch "$SENTINEL_FILE"
chmod 640 "$SENTINEL_FILE"
chown root:docker "$SENTINEL_FILE"

log "Hatchet token generated successfully"

# Start greptile compose stack now that token exists (best-effort)
if /usr/bin/systemctl list-unit-files | grep -q '^greptile-compose.service'; then
  log "Triggering greptile-compose.service start"
  /usr/bin/systemctl start greptile-compose.service || true
fi
