apiVersion: v1 
kind: ConfigMap
metadata:
  name: indexer-config
data:
  AWS_REGION: {{ .Values.global.region | quote }} # Only works in us-east-1 for bedrock
  HATCHET_CLIENT_TLS_STRATEGY: "none"
  VECTOR_DB_PROVIDER: {{ .Values.vectordb.config.provider | quote }}
  VECTOR_EMBEDDINGS_TABLE_NAME: "embeddings"
  VECTOR_DB_NAME: "vector"
  VECTOR_DB_HOST: {{ .Values.database.env.host | quote }}
  VECTOR_DB_PORT: {{ .Values.database.env.port | quote }}
  BATCH_SIZE: {{ .Values.indexer.config.batchSize | quote }}
  PARENT_DIR: {{ .Values.indexer.config.rootDir | quote }}
  LLM_TIMEOUT: {{ .Values.indexer.config.llmTimeout | quote }}
  {{- range $key, $value := .Values.indexer.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer-chunker-config
data:
  PORT: {{ .Values.indexer.service.chunker.port | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer-summarizer-config
data:
  PORT: {{ .Values.indexer.service.summarizer.port | quote }}
  SUMMARIZER_MODEL_PROVIDER: {{ .Values.indexer.config.summarizerModelProvider | quote }}
  SUMMARIZER_MODEL: {{ .Values.indexer.config.summarizerModel | quote }}
  EMBEDDINGS_MODEL_PROVIDER: {{ .Values.indexer.config.embeddingsModelProvider | quote }}
  EMBEDDINGS_MODEL: {{ .Values.indexer.config.embeddingsModel | quote }}
